export const mockMovies = [
  {
    id: 0,
    title: "The Godfather",
    genre: "Crime/Drama",
    posterURL: "https://image.tmdb.org/t/p/original/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    releaseDate: "1972-03-24",
    duration: 175,
    isFeatured: true,
    isTrending: true,
    isOriginal: true,
    rating: 9.2
  },
  {
    id: 1,
    title: "The Dark Knight",
    genre: "Action/Thriller",
    posterURL: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    videoURL: "http://localhost:8000/videos/1740176948983-colorized_preview_videomp4.m3u8",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    description: "When the Joker wreaks havoc on Gotham City, Batman must confront his greatest psychological and physical challenge.",
    releaseDate: "2008-07-18",
    duration: 152,
    isTrending: true,
    isOriginal: true,
    rating: 9.0
  },
  {
    id: 2,
    title: "Inception",
    genre: "Sci-Fi/Thriller",
    posterURL: "https://image.tmdb.org/t/p/original/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    description: "A thief who enters the dreams of others to steal secrets is offered a chance to plant an idea in a CEO's mind.",
    releaseDate: "2010-07-16",
    duration: 148,
    isTrending: true,
    rating: 8.8
  },
  {
    id: 3,
    title: "Pulp Fiction",
    genre: "Crime/Drama",
    posterURL: "https://image.tmdb.org/t/p/original/dM2w364MScsjFf8pfMbaWUcWrR.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    description: "Various interconnected stories of criminals in Los Angeles unfold in this nonlinear narrative masterpiece.",
    releaseDate: "1994-10-14",
    duration: 154,
    isOriginal: true,
    rating: 8.9
  },
  {
    id: 4,
    title: "The Lord of the Rings: The Return of the King",
    genre: "Fantasy/Adventure",
    posterURL: "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    description: "The final chapter where Frodo and Sam reach Mount Doom while Aragorn leads the forces of good against Sauron's army.",
    releaseDate: "2003-12-17",
    duration: 201,
    isTrending: true,
    rating: 8.9
  },
  {
    id: 5,
    title: "Spirited Away",
    genre: "Animation/Fantasy",
    posterURL: "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/AbgEQO2mneCSOc8CSnOMa8pBS8I.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    description: "A young girl wanders into a world of spirits where her parents are turned into pigs, and she must work to free them.",
    releaseDate: "2001-07-20",
    duration: 125,
    isOriginal: true,
    rating: 8.6
  },
  {
    id: 6,
    title: "Parasite",
    genre: "Thriller/Dark Comedy",
    posterURL: "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    description: "A poor family schemes to become employed by a wealthy household, entering a web of deception and class conflict.",
    releaseDate: "2019-05-30",
    duration: 132,
    isTrending: true,
    rating: 8.5
  },
  {
    id: 7,
    title: "Interstellar",
    genre: "Sci-Fi/Adventure",
    posterURL: "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    description: "Explorers travel through a wormhole in search of a new home for humanity, confronting cosmic wonders and existential questions.",
    releaseDate: "2014-11-07",
    duration: 169,
    rating: 8.6
  },
  {
    id: 8,
    title: "The Matrix",
    genre: "Sci-Fi/Action",
    posterURL: "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/7u3pxc0K1wx32IleAkLv78MKgrw.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "The Wachowskis",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    description: "A computer programmer discovers reality is a simulation and joins a rebellion against its AI controllers.",
    releaseDate: "1999-03-31",
    duration: 136,
    isOriginal: true,
    rating: 8.7
  },
  {
    id: 9,
    title: "Forrest Gump",
    genre: "Drama/Romance",
    posterURL: "https://image.tmdb.org/t/p/original/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/wM5tlDxBaFwLJ5IPhJ4hZtVk8Qm.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    description: "A man with low IQ witnesses and unwittingly influences several defining historical events in 20th-century America.",
    releaseDate: "1994-07-06",
    duration: 142,
    rating: 8.8
  },
  {
    id: 10,
    title: "The Avengers: Endgame",
    genre: "Action/Sci-Fi",
    posterURL: "https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Anthony & Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    description: "The Avengers team up to reverse Thanos' snap and restore balance to the universe in this epic conclusion.",
    releaseDate: "2019-04-26",
    duration: 181,
    isTrending: true,
    rating: 8.4
  },
  {
    id: 11,
    title: "Gladiator",
    genre: "Historical/Epic",
    posterURL: "https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/h5UzYZquMwO9FVn15R2eKQMitnW.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Ridley Scott",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    description: "A former Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.",
    releaseDate: "2000-05-05",
    duration: 155,
    rating: 8.5
  },
  {
    id: 12,
    title: "Joker",
    genre: "Psychological Thriller",
    posterURL: "https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    description: "A mentally troubled comedian descends into madness and becomes a psychopathic criminal mastermind.",
    releaseDate: "2019-10-04",
    duration: 122,
    isTrending: true,
    rating: 8.4
  },
  {
    id: 13,
    title: "The Social Network",
    genre: "Biography/Drama",
    posterURL: "https://image.tmdb.org/t/p/original/ok5Wh8385Kgblq9MSU4VGvazeMH.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/4g3gNfwiiq0t1kE5wV1k8JfH1MM.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "David Fincher",
    cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
    description: "The story of Mark Zuckerberg's creation of Facebook and the legal battles that followed its success.",
    releaseDate: "2010-10-01",
    duration: 120,
    rating: 7.7
  },
  {
    id: 14,
    title: "La La Land",
    genre: "Musical/Romance",
    posterURL: "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backgroundURL: "https://image.tmdb.org/t/p/original/6sbzyYgLI0x0KKE8V7kGhrBI7Ee.jpg",
    videoURL: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    description: "A jazz pianist and an aspiring actress pursue their dreams while navigating the challenges of a relationship in Los Angeles.",
    releaseDate: "2016-12-09",
    duration: 128,
    isOriginal: true,
    rating: 8.0
  }
];

export const bannerMovie = mockMovies[0];